-- 포르그래머스 SQL 고득점 Kit
-- JOIN

-- 없어진 기록 찾기
SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS O
    LEFT OUTER JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE I.INTAKE_CONDITION IS NULL
    ORDER BY ANIMAL_ID;

-- 있었는데요 없었습니다
SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS O
    LEFT OUTER JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE O.DATETIME < I.DATETIME
    ORDER BY I.DATETIME ASC;

-- 오랜 기간 보호한 동물(1)
SELECT I.NAME, I.DATETIME FROM ANIMAL_INS I
    LEFT OUTER JOIN ANIMAL_OUTS O
    ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE O.DATETIME IS NULL
    ORDER BY I.DATETIME ASC
    LIMIT 3;

-- 보호소에서 중성화한 동물
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME FROM ANIMAL_OUTS O
    LEFT OUTER JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
    WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
    ORDER BY O.ANIMAL_ID;