-- 포르그래머스 SQL 고득점 Kit
-- SUM, MAX, MIN

-- 최댓값 구하기
SELECT DATETIME "시간" FROM ANIMAL_INS
    ORDER BY DATETIME DESC
    LIMIT 1;

-- 최솟값 구하기
SELECT DATETIME "시간" FROM ANIMAL_INS
    ORDER BY DATETIME
    LIMIT 1;

-- 동물 수 구하기
SELECT COUNT(ANIMAL_ID) FROM ANIMAL_INS;

-- 중복 제거하기
SELECT COUNT(DISTINCT NAME) "count" FROM ANIMAL_INS